### ISSUE TITLE
eliminate a issue subbmited in mobile version

### ISSUE THREAD

**Issue by llaporta** [MKLab-ITI/ImproveMyCity-Mobile#1]
hi, i have a question, how can user does to eliminate an issue reported after submitted in the mobile version?

for example, if the user make a mistake when select a picture from his memory card and he sent the problem

**Comment by jimver04** [comment]
Hi,
Delete can only be done from the back-end of joomla.

Dimitrios

On 4/7/2014 5:22 μμ, llaporta wrote:

> hi, i have a question, how can user does to eliminate an issue 
> reported after submitted in the mobile version?
> 
> for example, if the user make a mistake when select a picture from his 
> memory card and he sent the problem
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MKLab-ITI/ImproveMyCity-Mobile/issues/1.

## 

Dimitrios Ververidis, Dr.
Post-doctoral Researcher,
Information Technologies Institute, ITI-CERTH,
Thermi, Thessaloniki, Greece
✉: ververid@iti.gr,
WWW:  http://iti.gr/iti/people/Dimitrios_Ververidis.html
Blog: http://dimitriosververidis.blogspot.com
PO BOX 60361, 57001, ☏: 2311/257784
FAX: 2310/474128

**Comment by llaporta** [comment]
It will be interesting that the user can delete your own issues in case that has made a mistake when submitted an issue

**Comment by jimver04** [comment]
It is better to state the comments in the IMC-mobile google group: https://groups.google.com/forum/#!forum/improvemycity-mobile

The deletion of an issue is in the todo list but other things have higher priority. Check also our new site http://www.improve-my-city.com 

BR,
Dimitrios
