### ISSUE TITLE
error  if import to android studio

### ISSUE THREAD

**Issue by lungkao** [MKLab-ITI/ImproveMyCity-Mobile#2]
- Project ImproveMyCity_Project:/Users/lungkao/AndroidstudioProjects/ImproveMyCity_Project/project.properties:
  Library reference ../../google-play-services_lib could not be found
  Path is /Users/lungkao/AndroidstudioProjects/ImproveMyCity_Project/../../google-play-services_lib which resolves to /Users/lungkao/google-play-services_lib

**Comment by jimver04** [comment]
Make sure that you download the latest IMC for Android Studio.
The path should not exceed 256 characters.
