### ISSUE TITLE
Wrong username and password

### ISSUE THREAD

**Issue by sara223** [MKLab-ITI/ImproveMyCity-Mobile#3]
Hi,
  Iam trying to connect my web server   http://smartsystemadmin.byethost7.com/index.php/ssac
with the application ..here is my code 
    public static String COM_Protocol_S = "http://"; 

```
public static String ServerSTR      =  "smartsystemadmin.byethost7.com";

/** Server path of application */
public static String phpExec        = "/ssac";

/** Server path of issue images */ 
public static String remoteImages   = "/";
 * */
public static String EncKey =  "1234567890123456";
```

now i'am able to register and registration data already saved on my server database but i can't log-in the app
it shows me wrong username and password..
note //i'am using eclipse version of IMCity and joomla 2.5.7 
??Do i have to use https instead of http
?and do i have to get SSL certificate 
where do you think the problem that makes the app keeps showing me wrong username and password while they are true.

also when i run the app and got the wrong username and password message the logCat shows : java.lang.String can not be converted to Joson0bject

**Comment by jimver04** [comment]
This question was answered privately. I am updating github with a small delay. I am just let you know that the bug was the Joomla version. You needed >2.5.17 to have the login working correctly.
